# Generated by Django 5.0.6 on 2024-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_links_logo', models.CharField()),
                ('personal_links_link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_img', models.ImageField(upload_to='personal_info')),
                ('personal_name', models.CharField()),
                ('personal_work_Field', models.TextField()),
            ],
        ),
    ]
