# Generated by Django 5.0.6 on 2024-07-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_work_Field', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='personal_work_Field',
        ),
    ]
