# Generated by Django 5.0.6 on 2024-07-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0002_personal_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personal_Field',
        ),
    ]
