# Generated by Django 5.0.6 on 2024-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_or_University_name', models.CharField()),
                ('Degree_or_Diploma_name', models.CharField()),
                ('Passing_Year', models.CharField()),
            ],
        ),
    ]
