# Generated by Django 5.0.6 on 2024-07-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default=None)),
                ('services_logo', models.CharField()),
                ('services_title', models.CharField()),
                ('services_description', models.TextField()),
            ],
        ),
    ]
