# Generated by Django 5.0.6 on 2024-07-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField()),
                ('Address', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_num', models.IntegerField(max_length=10)),
                ('Freelance', models.CharField()),
            ],
        ),
    ]
