# Generated by Django 5.0.6 on 2024-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetinTouch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='Phone_num',
            field=models.IntegerField(),
        ),
    ]
