# Generated by Django 5.0.6 on 2024-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetinTouch', '0002_alter_contactdetails_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='Phone_num',
            field=models.CharField(blank=True),
        ),
    ]
