# Generated by Django 5.0.6 on 2024-07-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_logo', models.CharField(default=None)),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services', models.TextField(help_text='Enter services separated by commas')),
                ('purchase', models.CharField(max_length=100)),
            ],
        ),
    ]
