# Generated by Django 4.2.3 on 2024-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_id', models.CharField(default=None, max_length=100)),
                ('Banner_img', models.FileField(default=None, upload_to='Projects/Banner')),
                ('Banner_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manipulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manipulation_id', models.CharField(default=None, max_length=100)),
                ('Manipulation_img', models.FileField(default=None, upload_to='Projects/Manipulation')),
                ('Manipulation_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socialmedia_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Socialmedia_Post_id', models.CharField(default=None, max_length=100)),
                ('Socialmedia_Post_img', models.FileField(default=None, upload_to='Projects/Post')),
                ('Socialmedia_Post_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Web_Development_id', models.CharField(default=None, max_length=100)),
                ('Web_Development_img', models.FileField(default=None, upload_to='Projects/Web_Development')),
                ('Web_Development_title', models.CharField(max_length=100)),
                ('Web_Development_Link', models.CharField(max_length=2000)),
            ],
        ),
    ]
